ASP_NET_Core_MVC_My_Tests/Models/ArrayModel.cs
namespace ASP_NET_Core_MVC_My_Tests.Models
{
	public class ArrayModel
	{
		public List<int>? AllNumbers { get; set; }
		public List<int>? EvenNumbers { get; set; }
		public List<int>? OddNumbers { get; set; }
	}
}

ASP_NET_Core_MVC_My_Tests/Models/ErrorViewModel.cs
namespace ASP_NET_Core_MVC_My_Tests.Models
{
	public class ErrorViewModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

ASP_NET_Core_MVC_My_Tests/Controllers/ArrayController.cs
using ASP_NET_Core_MVC_My_Tests.Models;
using Microsoft.AspNetCore.Mvc;

namespace ASP_NET_Core_MVC_My_Tests.Controllers
{
	public class ArrayController : Controller
	{
		//public IActionResult Index()
		//{
		//	// Создаём массив чисел от 100 до 999
		//	List<int> numbers = new List<int>();
		//	for (int i = 100; i <= 999; i++)
		//	{
		//		numbers.Add(i);
		//	}

		//          //// Преобразуем числа в строки и объединяем их
		//          //string numbersAsString =string.Join(",", numbers);

		//          //// Передаем строку с числами в представление
		//          //ViewBag.Numbers=numbersAsString;

		//          // Возвращаем представление с массивом чисел в качестве модели
		//          return View(numbers);
		//}


		// рабочий вариант без создания списка
		public IActionResult Index()
		{
			int start = 1;
			int end = 9999;
			int size = 200;

			// Создаём массив случайных чисел            
			int[] numbersArray = new int[size];

			// генерируем случайные числа в заданном диапазоне
			Random random = new Random();
			for (int i = 0; i < size; i++)
			{
				numbersArray[i] = random.Next(start, end + 1);
			}

			List<int> allNumbersList = new List<int>(numbersArray);
			List<int> evenNumbersList = new List<int>();
			List<int> oddNumbersList = new List<int>();

			var viewModel = new ArrayModel
			{
				AllNumbers = allNumbersList,
				EvenNumbers = evenNumbersList,
				OddNumbers = oddNumbersList
			};

			int quantityEven = 0;
			int quantityOdd = 0;
			int maxNumber = numbersArray[0];
			int minNumber = numbersArray[0];
            int maxEvenNumber = numbersArray[0];
            int minEvenNumber = numbersArray[0];
            int maxOddNumber = numbersArray[0];
            int minOddNumber = numbersArray[0];


            foreach (var number in allNumbersList)
            {
                if (number % 2 == 0)
                {
                    evenNumbersList.Add(number);
                    quantityEven++;
                }
                else
                {
                    oddNumbersList.Add(number);
                    quantityOdd++;
                }
				
				if (number>maxNumber)
				{
					maxNumber=number;	
				}

				if (number < minNumber)
				{
					minNumber=number;
				}
            }
			
			foreach (var number in evenNumbersList)
			{
				if(number>maxEvenNumber)
				{
					maxEvenNumber = number;
				}
				if(number<minEvenNumber)
				{
					minEvenNumber = number;
				}
			}

            foreach (var number in oddNumbersList)
            {
                if (number > maxOddNumber)
                {
                    maxOddNumber = number;
                }
                if (number < minOddNumber)
                {
                    minOddNumber = number;
                }
            }

            ViewBag.Start = start;
			ViewBag.End = end;
			ViewBag.Size = size;
			ViewBag.QuantityEven = quantityEven;
			ViewBag.QuantityOdd = quantityOdd;
			ViewBag.MaxNumber = maxNumber;
			ViewBag.MinNumber = minNumber;
            ViewBag.MaxEvenNumber = maxEvenNumber;
            ViewBag.MinEvenNumber = minEvenNumber; 
			ViewBag.MaxOddNumber = maxOddNumber;
            ViewBag.MinOddNumber = minOddNumber;

            return View(viewModel);
		}


		//// рабочий вариант без создания списка
		//public IActionResult Index()
		//{
		//    int start = 1000;
		//    int end = 9999;
		//    int size = 1000;

		//    // Создаём массив случайных чисел            
		//    int[] numbers=new int[size];

		//    // генерируем случайные числа в заданном диапазоне
		//    Random random = new Random();
		//    for (int i = 0; i < size; i++)
		//    {
		//        numbers[i] = random.Next(start, end + 1);
		//    }

		//    ViewBag.Start = start;
		//    ViewBag.End = end;

		//    return View(numbers);
		//}

		//public IActionResult Index(int? start,int? end)
		//{
		//    start ??= 1000;
		//    end ??= 9999;

		//    // Создаём массив чисел от 100 до 999
		//    List<int> numbers = new List<int>();
		//    for (int i = start.Value; i <= end.Value; i++)
		//    {
		//        numbers.Add(i);
		//    }

		//    ViewBag.Start=start;
		//    ViewBag.End=end;

		//    return View(numbers);
		//}
	}
}

ASP_NET_Core_MVC_My_Tests/Controllers/HomeController.cs
using ASP_NET_Core_MVC_My_Tests.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ASP_NET_Core_MVC_My_Tests.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

ASP_NET_Core_MVC_My_Tests/Views/Array/Index.cshtml
@model ArrayModel

<!DOCTYPE html>
<html>
<head>
    <title>Numbers</title>
</head>
<body>
    <h2>This array is fixed in NumbersControllers</h2>
    <hr />
    <h3>Array of @ViewBag.Size numbers from @ViewBag.Start to @ViewBag.End, min number is @ViewBag.MinNumber, max number is @ViewBag.MaxNumber</h3>

    @* @{
    int lineNumber = 1;
    } *@

    @foreach (var number in Model.AllNumbers)
    {
        @number
        @:
    }
    <br />
    <hr />
    <h3>Even numbers in  the array above, total @ViewBag.QuantityEven, min number is @ViewBag.MinEvenNumber, max number is @ViewBag.MaxEvenNumber</h3>

    @foreach (var number in Model.EvenNumbers)
    {
        @number
        @:
    }

    <br />
    <hr />
    <h3>Odd numbers in  the array above, total @ViewBag.QuantityOdd, min number is @ViewBag.MinOddNumber, max number is @ViewBag.MaxOddNumber</h3>

    @foreach (var number in Model.OddNumbers)
    {
        @number
        @:
    }

    <br />
    <hr />
    <br />
</body>
</html>

ASP_NET_Core_MVC_My_Tests/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ASP_NET_Core_MVC_My_Tests/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ASP_NET_Core_MVC_My_Tests</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ASP_NET_Core_MVC_My_Tests.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ASP_NET_Core_MVC_My_Tests</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Array" asp-action="Index">Arrays</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ASP_NET_Core_MVC_My_Tests - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>